name: Fetch Games by Creators

on:
  workflow_dispatch:

jobs:
  fetch-games:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run fetch-by-creator.py
        run: |
          cd python
          python fetch-games-by-creators.py 

      - uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "Added games for creators"