name: Fetch Games by Creator

on:
  workflow_dispatch:
    inputs:
      creator:
        description: "The creator's username to fetch games for"
        required: true
        type: string

jobs:
  fetch-games:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run fetch-by-creator.py
        run: |
          cd python
          python fetch-by-creator.py "${{ github.event.inputs.creator }}"

      - uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          commit_message: "Added games for creator ${{ github.event.inputs.creator }}"
